### ISSUE TITLE
MovedGate causes problems with dispatching

### ISSUE THREAD

**Issue by npoirie1** [SnowflurrySDK/Snowflurry.jl#224]
The introduction of `MovedGate` leads to problems with dispatching. Although `is_gate_type` can identify the type of the original `AbstractGate` which has been moved, `isa` sees a `MovedGate` and not the original gate. Therefore, any function that relies on dispatching to find the correct implementation will fail if a `MovedGate` is passed.

I think that modifying the original gates directly when moving them is better than creating a `MovedGate`. Users will expect dispatching to work for `AbstractGates`. The cost of adding a `move_gate` function to each gate is small in comparison in my opinion.

**Comment by npoirie1** [comment]
@plerouxanyon, what are your thoughts on this issue?

**Comment by plerouxanyon** [comment]
Hi Nicholas,

Thanks for raising the issue.

Is there someplace in Snowflake that has this issue, or are you referring to the more general issue? It would be much easier to discuss if you could give me a concrete use case example where a user will rely on dispatch outside of Snowflake.

**Comment by npoirie1** [comment]
In Snowflake, functions such as `cast_to_cz(gate::Snowflake.ControlX)::AbstractVector{AbstractGate}` fail if the gate has been moved. A workaround if we keep `MovedGate` is to remove the restriction to `Snowflake.ControlX` for the function argument and use `is_gate_type` before calling the function.

**Comment by npoirie1** [comment]
A user who creates their own gate may want to transpile their gate into native gates. They might use dispatching in the transpiler to do so. This would be a problem if the gate has been moved before the transpiler is called. They would have to use `is_gate_type` instead.

**Comment by plerouxanyon** [comment]
I see. I suspect there will also be other bugs like this in the transpiler. We certainly need more tests involving moved gates.

The real culprit is that we grouped the gate details (Hadamard gate type with this operator etc.) and placement details (connected to this qubit) into the gate abstraction.

We will also run into a very similar issue with aliased gates because we are dispatching on gates instead of operators.

Fixing the root issue is not a trivial amount of work (split gate and placement information), and the best will be to have a meeting on this with @alireza-najafi Monday.

**Comment by fSosaRey** [comment]
a simpler solution would be to define cast_to_cz(gate::Snowflake.MovedControlledGate) which dispatches to cast_to_cz(gate::Snowflake.ControlX) and analogous definitions where dispatch occurs on concrete types of AbstractGate

**Comment by plerouxanyon** [comment]
@fSosaRey Yes, that is also an option.

We now have three options.

1. move `move_gate` into the gate abstraction (more work for new gates)
2. handle `MovedGate` and `MovedControlledGate` correctly in the transpilers (more work for transpiler stages)
3. separate placement and gate information (more work now, but no extra work for new gates and transpilers later)

I expect that both creating gates and transpilers will be common, and I would prefer option number 3, but I am unsure whether it is wise to prioritize that given other deadlines. I am leaning towards option 2 (the least amount of work, and it is essentially fixing bugs rather than changing the architecture) with scheduling option 3 for later.

**Comment by plerouxanyon** [comment]
@npoirie1

Hi Nick,

We had a quick meeting with Ali early this morning. We decided that we are going to go with separating the placement and gate information (Option nr. 3 from earlier).

The structure we are going for will look something like the following.

```julia
struct PlacedGate begin
    gate::AbstractGate
    connected_qubits::Vector{Int}
end

struct H <: AbstractGate begin
end

get_operator(gate::H)::AbstractOperator = DenseOperator([...])
get_num_connected_qubits(gate::H)::Int = 1

struct Rz <: AbstractGate begin
    phase::Real
end
```

I hope to have this done by the end of next week.

**Comment by npoirie1** [comment]
That looks good to me. That's also what I had in mind.
