### ISSUE TITLE
Hello, Snowflurry world?

### ISSUE THREAD

**Issue by bsiegelwax** [SnowflurrySDK/Snowflurry.jl#303]
Copying and pasting

```
push!(c, [hadamard(1)])
push!(c, [control_x(1, 2)])

print(c)
```

from the ReadMe of this repository generates

```
MethodError: no method matching push!(::QuantumCircuit, ::Vector{Gate{Snowflurry.Hadamard}})

Closest candidates are:
  push!(::Any, ::Any, ::Any)
   @ Base abstractarray.jl:3387
  push!(::Any, ::Any, ::Any, ::Any...)
   @ Base abstractarray.jl:3388
  push!(::DataStructures.BinaryHeap, ::Any)
   @ DataStructures /opt/.julia/packages/DataStructures/MKv4P/src/heaps/binary_heap.jl:90
  
Stacktrace:
 [1] top-level scope
   @ In[6]:1
```
   
within the qBraid portal: https://lab.qbraid.com/

**Comment by plerouxanyon** [comment]
Good morning Brian,

The correct code snippet should read

```julia
push!(c, hadamard(1))
push!(c, control_x(1, 2))
```

We overlooked the readme when updating the `push!` function to conform to Julia's `Base.push!`. See #200 for more information regarding the specific change. I will submit a PR that updates the readme in short order.

All the code in the [Snowflurry.jl documentation](https://snowflurrysdk.github.io/Snowflurry.jl/dev/index.html) is tested using [Documenter.jl](https://documenter.juliadocs.org/stable/), so that will all be in good working order. I recommend you start with the tutorials there if you are experimenting with Snowflurry.

If you need anything else to get up and running with Snowlfurry, please do reach out.
Paul
